name: ChainMining
main: cn.lanink.chainmining.ChainMining
version: "1.3.0-SNAPSHOT"
api: ["1.0.0"]
load: POSTWORLD
author: "LT_Name"

commands:
  chainmining:
    description: "§aChainMining Command"
    usage: "§a/ChainMining §eOpen GUI"
    permission: chainmining.user

permissions:
  chainmining.user:
    default: true