name: ChainMining
main: cn.lanink.chainmining.ChainMining
version: "1.0.0"
api: ["1.0.0"]
load: POSTWORLD
author: "LT_Name"

commands:
  chainmine:
    description: "§aChainMining Command"
    usage: "§a/ChainMining §eOpen GUI"
    permission: chainmining.user

permissions:
  chainmine.user:
    default: true